# Generated by Django 3.2.4 on 2021-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='Shadya', max_length=80),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='Shadya', max_length=80),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='Shadya', max_length=80),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='Shadya', max_length=80),
        ),
    ]
